codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        # basic
        target: 80%
        threshold: 2%
        base: auto
        # advanced
        branches: []
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: []
        paths: []
      components:
        paths:
          - "src/components/"
        target: 85%
      services:
        paths:
          - "src/services/"
        target: 90%
    patch:
      default:
        # basic
        target: 80%
        threshold: 2%
        base: auto
        # advanced
        branches: []
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: []
        paths: []

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
  branches: null
