name: "Configuration Security Scan"

# Definición de permisos mínimos necesarios
permissions:
  contents: read
  security-events: write

on:
  push:
    branches: [ "master" ]
    paths:
      - '**/*.json'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.xml'
      - '**/*.ini'
      - '**/*.conf'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**/*.json'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.xml'
      - '**/*.ini'
      - '**/*.conf'
  schedule:
    - cron: '0 0 * * 2'  # Ejecutar cada martes a medianoche

jobs:
  config-scan:
    name: Configuration Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install KICS
        run: |
          curl -L -o kics.tar.gz https://github.com/Checkmarx/kics/releases/download/v1.6.1/kics_1.6.1_linux_x64.tar.gz
          tar -xzf kics.tar.gz || (echo "Fallo al descomprimir KICS" && exit 1)
          chmod +x kics || (echo "No se pudo hacer ejecutable KICS" && exit 1)

      - name: Run KICS scan
        run: |
          ./kics scan -p . -o kics-results.json --report-formats json,sarif --exclude-severities info,low --exclude-paths ".github/workflows"

      - name: Upload KICS scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
          category: kics
        if: always()
        continue-on-error: true
