name: Deploy Simple

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          echo "Preparando entorno para despliegue..."
          mkdir -p logs
          mkdir -p backend-call-automation
          mkdir -p frontend-call-automation

      - name: Create necessary files
        run: |
          mkdir -p logs
          touch logs/deploy.log

      - name: Deploy application
        run: |
          echo "Desplegando aplicación..."
          echo "$(date): Iniciando despliegue" >> logs/deploy.log
          # Simular un despliegue exitoso
          sleep 2
          echo "$(date): Despliegue completado exitosamente" >> logs/deploy.log
          echo "Despliegue completado exitosamente."

      - name: Create test log file
        run: |
          touch logs/tests.log

      - name: Run tests
        run: |
          echo "Ejecutando pruebas post-despliegue..."
          echo "$(date): Iniciando pruebas" >> logs/tests.log
          # Simular pruebas exitosas
          sleep 1
          echo "$(date): Pruebas completadas exitosamente" >> logs/tests.log
          echo "Pruebas completadas exitosamente."

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: deployment-logs
          path: |
            logs/deploy.log
            logs/tests.log
