name: Deploy / Rollback on Failure

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          echo "Preparando entorno para despliegue..."
          echo "Creando directorios necesarios..."
          mkdir -p logs
          mkdir -p backend-call-automation
          mkdir -p frontend-call-automation

      - name: Deploy application
        id: deploy
        run: |
          echo "Desplegando aplicación..."
          echo "$(date): Iniciando despliegue" >> logs/deploy.log
          
          # Simular despliegue exitoso
          echo "$(date): Despliegue completado exitosamente" >> logs/deploy.log
          echo "Despliegue completado exitosamente."

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: deployment-logs
          path: logs/deploy.log

  rollback:
    name: Rollback on Failure
    needs: deploy
    runs-on: ubuntu-latest
    if: always() && needs.deploy.result == 'failure'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          echo "Preparando entorno para rollback..."
          echo "Creando directorios necesarios..."
          mkdir -p logs

      - name: Execute rollback
        run: |
          echo "Iniciando rollback..."
          echo "$(date): Iniciando rollback" >> logs/rollback.log
          
          # Simular rollback exitoso
          echo "$(date): Rollback completado exitosamente" >> logs/rollback.log
          echo "Rollback completado exitosamente."

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: rollback-logs
          path: logs/rollback.log
