name: Disable All Workflows

on:
  workflow_dispatch:

jobs:
  disable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create marker file
        run: |
          echo "This file indicates that all workflows are disabled" > .github/workflows/DISABLED

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/workflows/DISABLED
          git commit -m "Disable all workflows temporarily" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
