name: Ultra Minimal Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-cov pytest-mock respx email-validator prometheus-client
          if [ -f backend-call-automation/requirements.txt ]; then
            pip install -r backend-call-automation/requirements.txt
          fi

      - name: Create logs directory
        run: |
          mkdir -p backend-call-automation/logs
          touch backend-call-automation/logs/app.log

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/backend-call-automation" >> $GITHUB_ENV

      - name: Run tests
        run: |
          cd backend-call-automation
          python -m pytest tests/ -v
